# Generated by Django 3.2.5 on 2021-07-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("published", models.DateField()),
                ("isbn", models.CharField(max_length=255)),
                ("pages", models.SmallIntegerField()),
                ("cover", models.URLField()),
                ("language", models.CharField(max_length=255)),
            ],
        ),
    ]
