# Generated by Django 3.2.5 on 2021-07-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="cover",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="books",
            name="isbn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="books",
            name="language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="books",
            name="pages",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="books",
            name="published",
            field=models.DateField(blank=True, null=True),
        ),
    ]
